[build]
  command = "yarn build" # the command you run to build this file
  publish = "build" # create-react-app builds to this folder, Netlify should serve all these files statically
  functions = "functions-build" # netlify-lambda builds to this folder AND Netlify reads functions from here
